version: "3.7"
services:
  streaming-server:
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
  streamer:
    build: ./streamer
    volumes:
      - ./streamer/stream.sh:/usr/local/bin/stream.sh
    entrypoint: /usr/local/bin/stream.sh
    environment:
      - RTMP_SERVER_URL=rtmp://streaming-server:1935/live
      - STREAM_NAME=bushitsuchan
    devices:
      - /dev/video0:/dev/video0

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  tunnel:
    build: ./tunnel
    working_dir: /app
    command: ash -c "npm install && npm start"
    volumes:
      - ./tunnel/src:/app
    environment:
      - AWS_API_NAME=bushitsuchan
      - AWS_REST_API_ID=${AWS_REST_API_ID}

      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_HOST=reverse-proxy:80

      - NGROK_REGION=jp
      - AWS_REGION=ap-northeast-1
    ports:
      - 4040:4040

  web:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm install && npm start"
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
      - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
      - WORKSTATION_ID=${WORKSTATION_ID}
    volumes:
      - ./web/src:/app
  slack:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm install && npm start"
    environment:
      - SLACK_BOT_ACCESS_TOKEN=${SLACK_BOT_ACCESS_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
    volumes:
      - ./slack/src:/app
  endpoint:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm install && npm start"
    volumes:
      - ./endpoint/src:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    # command: redis-server --appendonly yes --requirepass foobared
    volumes:
      - ./redis-data:/data
  # python:
