version: "3.7"
services:
  rtmp:
    image: tiangolo/nginx-rtmp
    container_name: bushitsuchan-rtmp_server
    ports:
      - 1935:1935
  broadcast:
    build: ./broadcast-server
    container_name: broadcast_server
    volumes:
      - ./broadcast-server/broadcast.sh:/usr/local/bin/broadcast.sh
    entrypoint: /usr/local/bin/broadcast.sh
    environment:
      RTMP_SERVER_URL: rtmp://rtmp:1935/live
      STREAM_NAME: bushitsuchan
    devices:
      - /dev/video0:/dev/video0
  redis:
    image: redis:alpine
    container_name: bushitsuchan-redis
    ports:
      - "6379:6379"
    # command: redis-server --appendonly yes --requirepass foobared
    volumes:
      - ./redis-data:/data
  data-server:
    image: node:alpine
    container_name: bushitsuchan-data-server
    working_dir: /app
    command: ash -c "npm install && npm start"
    volumes:
      - ./data-server:/app
  proxy:
    image: nginx:alpine
    container_name: bushitsuchan-proxy
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  web:
    image: node:alpine
    container_name: bushitsuchan-web
    working_dir: /app
    command: ash -c "npm install && npm start"
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      WORKSTATION_ID: ${WORKSTATION_ID}
    volumes:
      - ./web:/app
  slack:
    image: nginx:alpine
    container_name: bushitsuchan-slack
  tunnel:
    image: taichunmin/serveo
    container_name: bushitsuchan-tunnel
    tty: true
    stdin_open: true
    command: autossh -M 0 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -R bushitsuchan:80:proxy:80 serveo.net
  # aws-cli:
  # python:
