version: "3.7"
services:
  rtmp:
    container_name: rtmp_server
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
  # broadcast:
  #   container_name: broadcast_server
  #   build: ./broadcast-server
  #   volume: ./broadcast-server/broadcast.sh:/usr/local/bin/broadcast.sh
  #   environment:
  #     RTMP_SERVER_URL: "rtmp://rtmp:1935/live"
  #     STREAM_NAME: bushitsuchan
  #   devices:
  #     - /dev/video0:/dev/video0
  proxy:
    image: nginx
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  web:
    image: nginx
  slack:
    image: nginx
  # ngrok:
  # aws-cli:
  # python: