version: "3.7"
services:
  streaming-server:
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
  streamer:
    build: ./streamer
    volumes:
      - ./streamer/stream_debug.sh:/usr/local/bin/stream.sh
      - ./sample_movie.mp4:/sample_movie.mp4
    entrypoint: /usr/local/bin/stream.sh
    environment:
      - RTMP_SERVER_URL=rtmp://streaming-server:1935/live
      - STREAM_NAME=bushitsuchan
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    # command: redis-server --appendonly yes --requirepass foobared
    volumes:
      - ./redis-data:/data
  data-server:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm install && npm run dev"
    volumes:
      - ./data-server:/app
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  web:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm install && npm run dev"
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
      - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
      - WORKSTATION_ID=${WORKSTATION_ID}
    volumes:
      - ./web:/app
    ports:
      - 3000:80
  slack:
    image: nginx:alpine
    ports:
      - 3001:80
  tunnel:
    image: taichunmin/serveo
    container_name: bushitsuchan-tunnel
    tty: true
    stdin_open: true
    command: autossh -M 0 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -R bushitsuchan-dev:80:proxy:80 serveo.net
  # aws-cli:
  # python:
