version: "3.7"
services:
  rtmp:
    container_name: rtmp_server
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
  broadcast:
    container_name: broadcast_server
    build: ./broadcast-server
    volumes:
      - ./broadcast-server/broadcast.sh:/usr/local/bin/broadcast.sh
    entrypoint: /usr/local/bin/broadcast.sh
    environment:
      RTMP_SERVER_URL: "rtmp://rtmp:1935/live"
      STREAM_NAME: bushitsuchan
    # devices:
    #   - /dev/video0:/dev/video0
  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  web:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm install && npm start"
    volumes:
      - ./web:/app
  slack:
    image: nginx:alpine
  # ngrok:
  # aws-cli:
  # python: