version: "3.7"
services:
  rtmp:
    container_name: rtmp_server
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
  broadcast:
    container_name: broadcast_server
    build: ./broadcast-server
    depends_on:
      - rtmp
    environment:
      RTMP_SERVER_URL: "rtmp://rtmp:1935/live"
      STREAM_NAME: bushitsuchan
    devices:
      - "/dev/video0:/dev/video0"
  proxy:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  web:
    image: node
    ports:
      - "3000:3000"
  slack:
    image: node
    ports:
      - "3001:3001"
  # ngrok:
  # aws-cli:
  # python: