version: "3.7"
services:
  streaming-server:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm ci"
    volumes:
      - ../streaming-server/src:/app

  image-storage:
    build: ../image-storage
    working_dir: /app
    command: ash -c "npm ci"
    entrypoint: docker-entrypoint.sh
    volumes:
      - ../image-storage/src:/app

  hls:
    build: ../hls
    working_dir: /app
    command: ash -c "npm ci"
    entrypoint: docker-entrypoint.sh
    volumes:
      - ../hls/src:/app

  tunnel:
    build: ../tunnel
    working_dir: /app
    command: ash -c "npm ci"
    volumes:
      - ../tunnel/src:/app

  web:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm ci"
    volumes:
      - ../web/src:/app

  slack:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm ci"
    volumes:
      - ../slack/src:/app

  endpoint:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm ci"
    volumes:
      - ../endpoint/src:/app

  object-detection:
    build: ../object-detection
    working_dir: /app
    command: bash -c "pipenv sync --dev"
    volumes:
      - ../object-detection/src:/app
