version: "3.7"
services:
  streaming-server:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm install && npm audit fix"
    volumes:
      - ../streaming-server/src:/app

  media:
    build: ../media
    working_dir: /app
    command: ash -c "npm install && npm audit fix"
    entrypoint: docker-entrypoint.sh
    volumes:
      - ../media/src:/app

  tunnel:
    build: ../tunnel
    working_dir: /app
    command: ash -c "npm install && npm audit fix"
    volumes:
      - ../tunnel/src:/app

  web:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm install && npm audit fix"
    volumes:
      - ../web/src:/app

  slack:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm install && npm audit fix"
    volumes:
      - ../slack/src:/app

  endpoint:
    image: node:alpine
    working_dir: /app
    command: ash -c "npm install && npm audit fix"
    volumes:
      - ../endpoint/src:/app

  object-detection:
    build: ../object-detection
    working_dir: /app
    command: bash -c "pipenv install --dev && pipenv update"
    volumes:
      - ../object-detection/src:/app
